# Jenkins Plugins Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-plugins
  namespace: jenkins
data:
  plugins.txt: |-
    kubernetes:1.31.0
    workflow-cps:2803.v554558509a_d1
    git:4.11.5
    blueocean:1.27.0
    credentials:1311.v2306d7367663
    cloudbees-folder:6.858.v635564cdb_a_a_c