# jenkins-values.yaml
controller:
  image:
    repository: jenkins/jenkins
    tag: "2.518-jdk21"

  admin:
    existingSecret: jenkins-admin
    userKey: jenkins-admin-user
    passwordKey: jenkins-admin-password

  containerEnv:
    - name: DOCKERHUB_USERNAME
      valueFrom:
        secretKeyRef:
          name: dockerhub-credentials
          key: username
    - name: DOCKERHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: dockerhub-credentials
          key: password
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: github-ci-token
          key: token

  JCasC:
    enabled: true
    defaultConfig: false
    configScripts:
      main: |
        jenkins:
          systemMessage: "Bienvenido a Jenkins"
          securityRealm:
            local:
              allowsSignup: false
              enableCaptcha: false
              users:
                - id: "${JENKINS_ADMIN_USER}"
                  password: "${JENKINS_ADMIN_PASSWORD_HASH}"
          authorizationStrategy:
            loggedInUsersCanDoAnything:
              allowAnonymousRead: false

          clouds:
            - kubernetes:
                name: "kubernetes"
                serverUrl: "https://kubernetes.default"
                skipTlsVerify: true
                namespace: "jenkins"
                jenkinsUrl: "http://jenkins-local-k3d:8080"
                jenkinsTunnel: "jenkins-local-k3d-agent:50000"
                containerCap: 10
                connectTimeout: 5
                readTimeout: 15
                templates:
                  - name: "default"
                    label: "jenkins-agent"
                    nodeUsageMode: NORMAL
                    idleMinutes: 1

                    containers:
                      - name: jnlp
                        image: "jenkins/inbound-agent:3107.v665000b_51092-10"
                        args:
                          - ""
                        ttyEnabled: true
                        resourceRequestCpu: "100m"
                        resourceRequestMemory: "128Mi"
                        resourceLimitCpu: "500m"
                        resourceLimitMemory: "512Mi"

                      - name: nodejs
                        image: "node:18-alpine"
                        ttyEnabled: true
                        command:
                          - "cat"
                        alwaysPullImage: false
                        resourceRequestCpu: "100m"
                        resourceRequestMemory: "256Mi"
                        resourceLimitCpu: "500m"
                        resourceLimitMemory: "512Mi"

                      - name: kaniko
                        image: "gcr.io/kaniko-project/executor:v1.22.0"
                        ttyEnabled: true
                        alwaysPullImage: true
                        command:
                          - "/kaniko/executor"
                        args:
                          - "--help"
                        resourceRequestCpu: "250m"
                        resourceRequestMemory: "512Mi"
                        resourceLimitCpu: "1"
                        resourceLimitMemory: "1.5Gi"

                    volumes:
                      - secretVolume:
                          secretName: dockerhub-credentials
                          mountPath: "/kaniko/.docker"

        credentials:
          system:
            domainCredentials:
              - credentials:
                  - usernamePassword:
                      scope: GLOBAL
                      id: dockerhub-credentials
                      username: "${DOCKERHUB_USERNAME}"
                      password: "${DOCKERHUB_TOKEN}"
                      description: "DockerHub Access Token for CI/CD"
                  - usernamePassword:
                      scope: GLOBAL
                      id: github-ci-token
                      username: dummy
                      password: "${GITHUB_TOKEN}"
                      description: "GitHub Token for Push from Jenkins"

        unclassified:
          location:
            adminAddress: "admin@jenkins.local"
            url: "http://jenkins.local"

  sidecars:
    configAutoReload:
      enabled: false

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - docker-workflow
    - configuration-as-code
    - credentials
    - plain-credentials
    - credentials-binding
    - ssh-credentials
    - github-oauth
    - role-strategy

persistence:
  enabled: true
  storageClass: local-path
  size: 8Gi