# jenkins-values.template.yaml
# ---------------------------------------------------------------------------
# Jenkins Helm chart – plantilla para envsubst
#   • Agentes: nodejs & kaniko
#   • Secreto dockerhub‑config montado en /kaniko/.docker
# ---------------------------------------------------------------------------
controller:
  image:
    repository: jenkins/jenkins
    tag: "2.518-jdk21"

  # Credenciales de administrador (se crean con el script)
  admin:
    existingSecret: jenkins-admin
    userKey: jenkins-admin-user
    passwordKey: jenkins-admin-password

  # Variables internas del controller
  env:
    JENKINS_ADMIN_USER: "${JENKINS_ADMIN_USER}"
    JENKINS_ADMIN_PASSWORD_HASH: "${JENKINS_ADMIN_PASSWORD_HASH}"

  # Variables extra para plugins
  containerEnv:
    - name: DOCKERHUB_USERNAME
      value: "${DOCKERHUB_USERNAME}"
    - name: DOCKERHUB_TOKEN
      value: "${DOCKERHUB_TOKEN}"
    - name: GITHUB_TOKEN
      value: "${GITHUB_TOKEN}"

  # -------------------------------------------------------------------------
  # Jenkins Configuration as Code (JCasC)
  # -------------------------------------------------------------------------
  JCasC:
    enabled: true
    defaultConfig: false
    configScripts:
      main: |
        jenkins:
          systemMessage: "🚀 Jenkins sobre K3d/K3s – DevOps ready"

          securityRealm:
            local:
              allowsSignup: false
              enableCaptcha: false
              users:
                - id: "${JENKINS_ADMIN_USER}"
                  password: '${JENKINS_ADMIN_PASSWORD_HASH}'

          authorizationStrategy:
            loggedInUsersCanDoAnything:
              allowAnonymousRead: false

          # ------------- Kubernetes cloud (agentes en pods) -----------------
          clouds:
            - kubernetes:
                name: "kubernetes"
                serverUrl: "https://kubernetes.default"
                skipTlsVerify: true
                namespace: "jenkins"
                jenkinsUrl: "http://jenkins-local-k3d:8080"
                jenkinsTunnel: "jenkins-local-k3d-agent:50000"
                templates:
                  - name: "default"
                    label: "default"
                    idleMinutes: 1

                    containers:
                      # -------- Contenedor Node.js --------------------------
                      - name: "nodejs"
                        image: "node:18-alpine"
                        command: "cat"
                        ttyEnabled: true

                      # -------- Contenedor Kaniko ---------------------------
                      - name: "kaniko"
                        image: "gcr.io/kaniko-project/executor:v1.23.0-debug"
                        command: "/busybox/cat"
                        ttyEnabled: true
                        envVars:
                          - envVar:          # 👈 Sintaxis correcta
                              key: "DOCKER_CONFIG"
                              value: "/kaniko/.docker"

                    # ---- Volumen secreto con credenciales DockerHub --------
                    volumes:
                      - secretVolume:
                          secretName: "dockerhub-config"
                          mountPath: "/kaniko/.docker"

        # -------------------- Credenciales globales -------------------------
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - usernamePassword:
                      id: "dockerhub-credentials"
                      username: "${DOCKERHUB_USERNAME}"
                      password: "${DOCKERHUB_TOKEN}"
                  - string:
                      id: "github-ci-token"
                      secret: "${GITHUB_TOKEN}"

# ---------------------------------------------------------------------------
# Persistencia: PVC local‑path (k3d/k3s)
# ---------------------------------------------------------------------------
persistence:
  enabled: true
  storageClass: local-path
  size: 8Gi
