controller:
  image:
    repository: jenkins/jenkins
    tag: "2.518-jdk21"
    pullPolicy: IfNotPresent

  # Usamos un secreto existente para la configuración del admin
  admin:
    existingSecret: jenkins-admin
    userKey: jenkins-admin-user
    passwordKey: jenkins-admin-password

  containerEnv:
    - name: JENKINS_ADMIN_USER
      valueFrom:
        secretKeyRef:
          name: jenkins-admin
          key: jenkins-admin-user
    - name: JENKINS_ADMIN_PASSWORD_HASH
      valueFrom:
        secretKeyRef:
          name: jenkins-admin
          key: jenkins-admin-password
    - name: DOCKERHUB_USERNAME
      valueFrom:
        secretKeyRef:
          name: dockerhub-credentials
          key: username
    - name: DOCKERHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: dockerhub-credentials
          key: password
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: github-ci-token
          key: token

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - docker-workflow
    - blueocean
    - configuration-as-code
    - credentials-binding
    - ssh-credentials
    - credentials
    - plain-credentials
    - active-directory
    - github-oauth
    - role-strategy
    - jwt-auth
    - authentication-tokens
    - url-auth-sso
    - configuration-as-code-support

  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "2000m"
      memory: "4Gi"

  JCasC:
    enabled: true
    defaultConfig: false
    configScripts:
      main: |
        jenkins:
          systemMessage: "Bienvenido a Jenkins"
          securityRealm:
            local:
              allowsSignup: false
              enableCaptcha: false
              users:
                - id: "${JENKINS_ADMIN_USER}"
                  password: "#jbcrypt:${JENKINS_ADMIN_PASSWORD_HASH}"
          authorizationStrategy:
            loggedInUsersCanDoAnything:
              allowAnonymousRead: false
          clouds:
            - kubernetes:
                name: "kubernetes"
                serverUrl: "https://kubernetes.default"
                skipTlsVerify: true
                namespace: "jenkins"
                jenkinsUrl: "http://{{ .Release.Name }}-jenkins:8080"
                jenkinsTunnel: "{{ .Release.Name }}-jenkins-agent:50000"
                containerCap: 10
                connectTimeout: 5
                readTimeout: 15
                templates:
                  - name: "default"
                    label: "jenkins-agent"
                    nodeUsageMode: "NORMAL"
                    idleMinutes: 1
                    containers:
                      - name: jnlp
                        image: "jenkins/inbound-agent"
                        args: "${computer.jnlpmac} ${computer.name}"
                        ttyEnabled: true
                        resourceRequestCpu: "100m"
                        resourceRequestMemory: "128Mi"
                        resourceLimitCpu: "500m"
                        resourceLimitMemory: "512Mi"

        unclassified:
          casc:
            initializationTimeout: 600

        credentials:
          system:
            domainCredentials:
              - credentials:
                  - usernamePassword:
                      id: "dockerhub-credentials"
                      username: "${DOCKERHUB_USERNAME}"
                      password: "${DOCKERHUB_TOKEN}"
                      description: "DockerHub Access Token for CI/CD"
                  - usernamePassword:
                      id: "github-ci-token"
                      username: "dummy"
                      password: "${GITHUB_TOKEN}"
                      description: "GitHub Token for Push from Jenkins"

  sidecars:
    configAutoReload:
      enabled: true

  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

  volumes:
    - name: docker-storage
      emptyDir: {}
    - name: docker-bin
      emptyDir: {}

  volumeMounts:
    - name: docker-bin
      mountPath: /usr/local/bin

  livenessProbe:
    httpGet:
      path: /login
      port: 8080
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 5

  readinessProbe:
    httpGet:
      path: /login
      port: 8080
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 3

  startupProbe:
    httpGet:
      path: /login
      port: 8080
    initialDelaySeconds: 120
    periodSeconds: 10
    failureThreshold: 12

agent:
  podName: "jenkins-agent"
  customJenkinsLabels:
    - jenkins-agent
  nodeUsageMode: NORMAL
  containers:
    - name: jnlp
      image: "jenkins/inbound-agent"
      ttyEnabled: true
  connectTimeout: 100
  runAsUser: 1000

persistence:
  enabled: true
  storageClass: local-path
  size: 8Gi

service:
  type: ClusterIP
  agentListenerPort: 50000
